In [120]:
import numpy as np
import numpy.typing as npt

def svd_test(target_points: npt.NDArray, current_points: npt.NDArray):
    # q: target
    q = np.array(target_points).transpose()
    # p: current
    p = np.array(current_points).transpose()

    # centroids
    cen_P = np.mean(p, axis=1).reshape(-1, 1)
    cen_Q = np.mean(q, axis=1).reshape(-1, 1)

    # positions relative to centroids ("centered vectors")
    X = p - cen_P
    Y = q - cen_Q

    # covariance matrix
    S = X @ Y.T
    U, sigma, Vt = np.linalg.svd(S)

    # diagonal matrix
    d = np.eye(Vt.T.shape[1])
    d[-1, -1] = np.linalg.det(Vt.T @ U.T)

    # rotation and translation
    R = Vt.T @ d @ U.T
    t = cen_Q - R @ cen_P

    M = np.concat((R, t), axis=1)
    M = np.concat((M, [[0, 0, 0, 1]]), axis=0)

    p2 = np.pad(p, ((0, 1), (0, 0)), constant_values=1)
    q2 = np.pad(q, ((0, 1), (0, 0)), constant_values=1)

    error2 = M @ p2 - q2
    print(error2[:-1])

    return R @ p + t

    error1 = (R @ p + t) - q

    MI = np.linalg.inv(M)
    print(MI @ M)

    print(np.abs(error1).sum())
    print(error1)
    print(np.abs(error2).sum())
    print(error2)

In [131]:
target = np.array([[0, 0, 0], [0, 0, 1], [0, 1, 1]])
actual = np.array([[5, 4, 5], [5, 5, 4], [5, 4, 4]])

p = svd_test(actual, target)

print(actual)
print(actual - p)

[[ 0.          0.          0.        ]
 [ 0.2408833  -0.2044165  -0.0364668 ]
 [ 0.07293359  0.2408833  -0.3138169 ]]
[[5 4 5]
 [5 5 4]
 [5 4 4]]
[[ 0.         -1.          0.        ]
 [ 0.7591167   0.2044165   0.0364668 ]
 [-0.07293359 -0.2408833   0.3138169 ]]


In [70]:
t = np.array([
    [0, 0, 0],
    [0, 0, 0],
    [0, 0, 0],
])

print(np.pad(t, ((0, 1), (0, 0)), constant_values=1))

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [1 1 1]]
