In [1]:
import numpy as np
from alignment import fit_template_points_to_observed

fit_template_points_to_observed(
    np.array([[0, 0, 0], [0, 0, 1], [0, 2, 0]]),
    np.array([[0, 0, 0], [0, 0, 2], [0, 1, 0]]),
)

[[ 1.          0.          0.          0.        ]
 [ 0.          1.          0.         -0.40792727]
 [ 0.          0.          1.          0.58863924]
 [ 0.          0.          0.          1.        ]]
[[ 1.          0.          0.          0.        ]
 [ 0.          1.          0.         -0.40792727]
 [ 0.          0.          1.          0.58863924]
 [ 0.          0.          0.          1.        ]]


array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.93632918,  0.35112344, -0.40792727],
       [ 0.        , -0.35112344,  0.93632918,  0.58863924],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])