In [2]:
from nanover.omni import OmniRunner
from nanover.omni.openmm import OpenMMSimulation

simulation = OpenMMSimulation.from_xml_path("../openmm/openmm_files/17-ala.xml")
runner = OmniRunner.with_basic_server(simulation)

runner.load(0)
runner.pause()
runner.print_basic_info()

Serving "ragzo: NanoVer iMD Server" (ws://localhost:57240), discoverable on all interfaces on port 54545
Available simulations:
0: "17-ala"


In [18]:
ADDRESS = "ws://localhost:57240"

In [8]:
from websockets.asyncio.client import connect

async with connect(ADDRESS) as websocket:
    data = await websocket.recv()
    print(data)

b'\x81\xa5state\x82\xa7updates\x81\xbcimd.velocity_reset_available\xc2\xa8removals\x90'


In [16]:
import msgpack
import pprint

async with connect(ADDRESS) as websocket:
    data = await websocket.recv()
    message = msgpack.unpackb(data)
    pprint.pp(message)
    data = await websocket.recv()
    message = msgpack.unpackb(data)
    pprint.pp(message)

{'frame': {'frame.index': 0,
           'system.simulation.counter': 0,
           'particle.positions': b'\x07\xf0V\xbe\xe7\x1d\xa7;\xe6?\x1eA'
                                 b's\xd7\x92\xbd\n\xd7\xa3;\xac\x8b\x1dA4\x807;'
                                 b'\xd8\xf0\xf4=9\xd6\x1eA\x8f\xe4r\xbd'
                                 b'\xbb\xb8M>\x9b\xe6\x1fAk+v\xbd,\xd4\x9a<'
                                 b'{\x14\x1bAF\x94v\xbe\xeb\xe2\xb6\xbd:#\x1eA'
                                 b'\x08\xac\\\xbe\x87\x16\xd9<\xe3\xc7\x1fA'
                                 b'\xd5\xe7\x8a\xbeo\xf0\x85=|a\x1dA'
                                 b'S\x05\xa3\xbc\xa3#\xb9\xbdq\x1b\x1eA'
                                 b'^\xba\t\xbe\xaa\xf1R\xbdDi\x1aA?W\xdb\xbd'
                                 b'h"\xec=\xdd\xb5\x1aA\x9aw\x1c=\xa3#9<'
                                 b'\x1aQ\x1aA^\xba\t>\xcaT\x01>\x9f\xcd\x1eA'
                                 b'-C\\>\xe7\x8ch>\xd5\xe7\x1fA\xde\x02\xa9>'
                

In [24]:
async with connect(ADDRESS) as websocket:
    async for data in websocket:
        message = msgpack.unpackb(data)
        if "frame" in message:
            FIRST_FRAME = message["frame"]
            break

pprint.pp(FIRST_FRAME)

{'frame.index': 0,
 'system.simulation.counter': 0,
 'particle.positions': b'\x07\xf0V\xbe\xe7\x1d\xa7;\xe6?\x1eAs\xd7\x92\xbd'
                       b'\n\xd7\xa3;\xac\x8b\x1dA4\x807;\xd8\xf0\xf4=9\xd6\x1eA'
                       b'\x8f\xe4r\xbd\xbb\xb8M>\x9b\xe6\x1fAk+v\xbd,\xd4\x9a<'
                       b'{\x14\x1bAF\x94v\xbe\xeb\xe2\xb6\xbd:#\x1eA'
                       b'\x08\xac\\\xbe\x87\x16\xd9<\xe3\xc7\x1fA'
                       b'\xd5\xe7\x8a\xbeo\xf0\x85=|a\x1dAS\x05\xa3\xbc'
                       b'\xa3#\xb9\xbdq\x1b\x1eA^\xba\t\xbe\xaa\xf1R\xbdDi\x1aA'
                       b'?W\xdb\xbdh"\xec=\xdd\xb5\x1aA\x9aw\x1c=\xa3#9<'
                       b'\x1aQ\x1aA^\xba\t>\xcaT\x01>\x9f\xcd\x1eA-C\\>'
                       b'\xe7\x8ch>\xd5\xe7\x1fA\xde\x02\xa9>p\xce\x88>Di\x1eA'
                       b'\x05\xc5\xaf>\x1a\xc0[>\xa6\x9b\x1cA:#\x8a>ff&>'
                       b'\x07\xf0!A\xa4p=>\x1aQZ=\xfd\xf6\x1dA\x08=\x1b>'
                       b'e\xaa\xa0>\xb8@ A9EG

In [29]:
POSITION_DATA = FIRST_FRAME["particle.positions"]
print(len(POSITION_DATA), len(POSITION_DATA) // 12, POSITION_DATA)

2076 173 b'\x07\xf0V\xbe\xe7\x1d\xa7;\xe6?\x1eAs\xd7\x92\xbd\n\xd7\xa3;\xac\x8b\x1dA4\x807;\xd8\xf0\xf4=9\xd6\x1eA\x8f\xe4r\xbd\xbb\xb8M>\x9b\xe6\x1fAk+v\xbd,\xd4\x9a<{\x14\x1bAF\x94v\xbe\xeb\xe2\xb6\xbd:#\x1eA\x08\xac\\\xbe\x87\x16\xd9<\xe3\xc7\x1fA\xd5\xe7\x8a\xbeo\xf0\x85=|a\x1dAS\x05\xa3\xbc\xa3#\xb9\xbdq\x1b\x1eA^\xba\t\xbe\xaa\xf1R\xbdDi\x1aA?W\xdb\xbdh"\xec=\xdd\xb5\x1aA\x9aw\x1c=\xa3#9<\x1aQ\x1aA^\xba\t>\xcaT\x01>\x9f\xcd\x1eA-C\\>\xe7\x8ch>\xd5\xe7\x1fA\xde\x02\xa9>p\xce\x88>Di\x1eA\x05\xc5\xaf>\x1a\xc0[>\xa6\x9b\x1cA:#\x8a>ff&>\x07\xf0!A\xa4p=>\x1aQZ=\xfd\xf6\x1dA\x08=\x1b>e\xaa\xa0>\xb8@ A9EG>\xdfO\r>(\x0f#AU\xc1\xa8>\xc0\xec\x9e=q\xac!A]\xdc\xa6>33s>\xdc\xd7"A`v\xcf>\x1aQ\xba>\xb0\x03\x1fA\xc5\xfe\x02?\xfd\xf6\xd5>\xbc\x96\x1dA"\xfd&?\xec/\xbb>6<\x1eAd],?l\t\x99>\xd9\xce\x1fAw\xbe\xff>\x00o\x11?F\xb6\x1dAr\x8a\xce>\x83/\xcc>c\x7f A.\x90\x00?\x0b$\xc8>\x13\xf2\x1bA\xf3\x8e\xd3>\x1a\xc0\x1b?\x10\xe9\x1cA\xa3\x92\xfa>\x07_\x18?\xe5a\x1fA\xc6\xdc\x15? c\x1e?\xf9\x0f\x1dA%\x06A?

In [31]:
import numpy as np

POSITIONS = np.frombuffer(POSITION_DATA, dtype=np.float32)
print(POSITIONS)

[-2.0990001e-01  5.1000002e-03  9.8906002e+00 -7.1699999e-02
  4.9999999e-03  9.8465996e+00  2.7999999e-03  1.1960000e-01
  9.9273005e+00 -5.9300002e-02  2.0090000e-01  9.9938002e+00
 -6.0100000e-02  1.8900000e-02  9.6925001e+00 -2.4079999e-01
 -8.9299999e-02  9.8836002e+00 -2.1550000e-01  2.6500000e-02
  9.9863005e+00 -2.7129999e-01  6.5399997e-02  9.8362999e+00
 -1.9900000e-02 -9.0400003e-02  9.8816996e+00 -1.3450000e-01
 -5.1500000e-02  9.6506996e+00 -1.0710000e-01  1.1530000e-01
  9.6694002e+00  3.8199998e-02  1.1300000e-02  9.6448002e+00
  1.3450000e-01  1.2630001e-01  9.9252005e+00  2.1510001e-01
  2.2710000e-01  9.9940996e+00  3.3010000e-01  2.6719999e-01
  9.9006996e+00  3.4330001e-01  2.1460000e-01  9.7880001e+00
  2.6980001e-01  1.6249999e-01  1.0121100e+01  1.8500000e-01
  5.3300001e-02  9.8727999e+00  1.5160000e-01  3.1380001e-01
  1.0015800e+01  1.9460000e-01  1.3800000e-01  1.0191200e+01
  3.2960001e-01  7.7600002e-02  1.0104600e+01  3.2589999e-01
  2.3750000e-01  1.01777

In [32]:
print(POSITIONS.reshape(-1, 3))

[[-2.0990001e-01  5.1000002e-03  9.8906002e+00]
 [-7.1699999e-02  4.9999999e-03  9.8465996e+00]
 [ 2.7999999e-03  1.1960000e-01  9.9273005e+00]
 [-5.9300002e-02  2.0090000e-01  9.9938002e+00]
 [-6.0100000e-02  1.8900000e-02  9.6925001e+00]
 [-2.4079999e-01 -8.9299999e-02  9.8836002e+00]
 [-2.1550000e-01  2.6500000e-02  9.9863005e+00]
 [-2.7129999e-01  6.5399997e-02  9.8362999e+00]
 [-1.9900000e-02 -9.0400003e-02  9.8816996e+00]
 [-1.3450000e-01 -5.1500000e-02  9.6506996e+00]
 [-1.0710000e-01  1.1530000e-01  9.6694002e+00]
 [ 3.8199998e-02  1.1300000e-02  9.6448002e+00]
 [ 1.3450000e-01  1.2630001e-01  9.9252005e+00]
 [ 2.1510001e-01  2.2710000e-01  9.9940996e+00]
 [ 3.3010000e-01  2.6719999e-01  9.9006996e+00]
 [ 3.4330001e-01  2.1460000e-01  9.7880001e+00]
 [ 2.6980001e-01  1.6249999e-01  1.0121100e+01]
 [ 1.8500000e-01  5.3300001e-02  9.8727999e+00]
 [ 1.5160000e-01  3.1380001e-01  1.0015800e+01]
 [ 1.9460000e-01  1.3800000e-01  1.0191200e+01]
 [ 3.2960001e-01  7.7600002e-02  1.01046